### PR TITLE
HttpClient Observe System properties

### PR DESCRIPTION
**Pull request by jdcaperon**
Alternative to #11 

This will enable you to use the following environment variables:
```
http.proxyHost
http.proxyPort
https.proxyHost
https.proxyPort
```
as well as others.

### CODE REVIEW

**Comment by jdcaperon** [comment]
Ready for review @renqingyou

**Comment by jdcaperon** [comment]
Bump @renqingyou

**Comment by groodt** [comment]
I am also looking for this functionality.

**Comment by jdcaperon** [comment]
bump @renqingyou

**Comment by dengshiwei** [comment]
@groodt @jdcaperon Thank you for your suggestion. We will consider it

**Comment by dengshiwei** [comment]
Thank you for your opinion, but we don't have the planning support for this feature at present. If you have this requirement, we suggest you modify the source code to realize it. At the same time, we suggest using concurrent logging consumer to collect data

**Comment by jdcaperon** [comment]
A regrettable decision, do you have any reasoning why you don't plan to support this?

**Pull request closed without merging**
